import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#0d631b",
        "primary-container": "#2e7d32",
        "on-primary": "#ffffff",
        "on-primary-container": "#cbffc2",
        "primary-fixed": "#a3f69c",
        "primary-fixed-dim": "#88d982",
        "on-primary-fixed": "#002204",
        "on-primary-fixed-variant": "#005312",
        "secondary": "#7a5900",
        "secondary-container": "#fdbc13",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6b4d00",
        "secondary-fixed": "#ffdea3",
        "secondary-fixed-dim": "#fdbc13",
        "on-secondary-fixed": "#261900",
        "on-secondary-fixed-variant": "#5d4200",
        "tertiary": "#565555",
        "tertiary-container": "#6e6d6d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f4f0f0",
        "tertiary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed": "#1c1b1b",
        "on-tertiary-fixed-variant": "#474646",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#f7fbf0",
        "on-background": "#181d17",
        "surface": "#f7fbf0",
        "on-surface": "#181d17",
        "surface-variant": "#e0e4da",
        "on-surface-variant": "#40493d",
        "surface-container": "#ebefe5",
        "surface-container-low": "#f1f5eb",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e5eadf",
        "surface-container-highest": "#e0e4da",
        "surface-bright": "#f7fbf0",
        "surface-dim": "#d7dbd2",
        "surface-tint": "#1b6d24",
        "outline": "#707a6c",
        "outline-variant": "#bfcaba",
        "inverse-surface": "#2d322b",
        "inverse-on-surface": "#eef2e8",
        "inverse-primary": "#88d982",
        "brand-black": "#111111",
        "brand-green": "#2E7D32",
        "brand-yellow": "#F4B400",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "stack-sm": "16px",
        "stack-md": "32px",
        "stack-lg": "64px",
        "gutter": "32px",
        "unit": "8px",
        "section-padding-desktop": "120px",
        "section-padding-mobile": "64px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-md": ["DM Serif Display", "serif"],
        "headline-lg": ["DM Serif Display", "serif"],
        "display-lg": ["DM Serif Display", "serif"],
        "display-lg-mobile": ["DM Serif Display", "serif"],
        "label-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "caption": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["68px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["44px", { lineHeight: "1.15", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["52px", { lineHeight: "1.15", fontWeight: "400" }],
        "headline-md": ["38px", { lineHeight: "1.2", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.75", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.7", fontWeight: "400" }],
        "label-lg": ["15px", { lineHeight: "1.0", letterSpacing: "0.01em", fontWeight: "600" }],
        "caption": ["13px", { lineHeight: "1.4", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [
    forms,
  ],
}
